name: AI code review

on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths-ignore:
            - '**.md'
            - '**.json'
            - '**.txt'

jobs:
    ai-review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-dept: 0

            - name: Setup Nodejs
              uses: actions/checkout@v3
              with:
                node-version: '18'

            - name: install all depenedencies
              run: npm ci

            - name: AI Code review
              uses: ./
              env: 
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
                GITHUB_API_KEY: ${{secrets.OPEN_API_KEY}}
              with:
                config-path: 'review.config.json'
                max-comments: '10'
                severity: 'all' 
